version: '3.8'  # Use the appropriate version for your Docker Compose installation

services:
  postgres:
    image: postgres:latest
    container_name: where_house
    environment:
      POSTGRES_DB: IOAPP
      POSTGRES_USER: postgres    # Set the database user
      POSTGRES_PASSWORD: postgres  # Set the database password
    ports:
      - "5432:5432"  # Map container port 5432 to the host machine